# نام این گردش کار (Workflow) که در تب Actions گیت‌هاب نمایش داده می‌شود
name: Build Flutter APK

# تعریف رویدادهایی که این گردش کار را فعال می‌کنند
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# تعریف کارهایی که باید انجام شوند
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # مرحله ۱: دانلود کردن سورس کد پروژه شما از ریپازیتوری
      - name: Checkout code
        uses: actions/checkout@v3

      # مرحله ۲: نصب Java Development Kit (JDK)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      # مرحله ۳: نصب Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # مرحله ۴: دانلود تمام پکیج‌ها
      - name: Get Flutter dependencies
        run: flutter pub get

      # مرحله ۵: ساخت فایل‌های APK
      - name: Build release APK
        run: flutter build apk --release --split-per-abi

      # مرحله ۶: آپلود کردن فایل‌های APK (با نسخه اصلاح شده)
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4  # <--- اینجا تغییر اصلی است! از v3 به v4 آپدیت شد
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk
