name: Build Flutter APK with Error Handling

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check for Outdated Dependencies
        run: flutter pub outdated

      - name: Clean the project (clear caches)
        run: flutter clean

      - name: Build Release APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk

      - name: Capture any errors (if present)
        if: failure()
        run: |
          echo "There were errors during the build process."
          flutter doctor -v
          flutter pub outdated
          exit 1
